### ISSUE TITLE
Initial version, port from Javascript

### ISSUE THREAD

**Issue by pwalsh** [okfn/datapackage-registry-py#1]
# Description

[We have a working implementation of this in Javascript](https://github.com/okfn/datapackage-registry-js).

We need a Python version.

The registry is just a simple CSV with entries for different types of "Data Package Profiles". The code basically gets the registry, and turns it into an array of objects. This array is then used by other libraries to use the information in the registry to do stuff (get a schema for a data package, for example).

# Tasks

* [x] Port existing Javascript functionality to Python
  * [x] Note the config options
* [x] Port existing test cases to Python
* [x] Write up basic documentation on how it works (eg: 1 paragraph, and an example)
* [x] Runs on Python 2.7.x and 3.3.x and above
  * [x] Use compat pattern that we use [here](https://github.com/okfn/goodtables/blob/master/goodtables/compat.py) [here](https://github.com/okfn/jsontableschema-py/blob/master/jsontableschema/compat.py) [here](https://github.com/okfn/spd-admin/blob/master/spd_admin/compat.py). This is based on some popular libs like [requests](https://github.com/kennethreitz/requests/blob/master/requests/compat.py), as well as the [Python porting guide](https://docs.python.org/3/howto/pyporting.html)
* [x] Publish to PyPI as `datapackage-registry`

**Comment by pwalsh** [comment]
@trickvi FYI.

**Comment by pwalsh** [comment]
@brew note I forgot to talk to you about Py2/3. I added a task to the list.

**Comment by brew** [comment]
Published to PyPI as 0.0.1 https://pypi.python.org/pypi/datapackage-registry

**Comment by vitorbaptista** [comment]
May we close this issue?
