### ISSUE TITLE
Refactor and publish

### ISSUE THREAD

**Issue by pwalsh** [okfn/datapackage-registry-py#10]
# Description

We've been using this lib in several ways over the last 6 weeks. We need to focus on any refactoring needed to solidify the API, and then publish an updated version to PYPI.

# Tasks

* [ ] Refactor API if needed? I'm particularly concerned that:
  * [x] User can work from local cache
  * [x] User can update from local cache
  * [ ] User can easily choose to work from the live registry. I **don't** think this should be a different API (different method) - it should just be a different config option (`local=True|False` or something)
* [x] Tests
* [ ] Publish to `pypi`

**Comment by vitorbaptista** [comment]
To allow the user to update her local cache, we have to:

1. Create a cache folder inside the user's home (which is different, depending on her OS). I remember seeing a Python package to make this easier, but I don't remember its name. Hopefully, it'll be well maintained and there'll be one for JavaScript as well;
2. Add the logic of updating/clearing the cache.

Given that we control the registry, and it's doesn't change often, I would suggest us to avoid this extra complexity by simply updating the cache ourselves following [these instructions](https://github.com/okfn/datapackage-registry-py#updating-the-local-schemas-cache) whenever the registry is changed. This way, if the user wants to get the latest cache, she could simply update the package itself.

**Comment by vitorbaptista** [comment]
For working with the live registry, the user needs to point to its CSV file when creating a `Registry`, as in:

```python
registry = datapackage_registry.Registry('http://schemas.datapackages.org/registry.csv')
registry.get('base')
```

There's no difference in using the main registry or a third-party registry.

**Comment by vitorbaptista** [comment]
Another option would be to pass the schema URL instead of its ID in the registry, as in:

```python
registry = datapackage_registry.Registry()
registry.get('https://raw.githubusercontent.com/dataprotocols/schemas/master/fiscal-data-package.json')
```

**Comment by vitorbaptista** [comment]
This repository is now deprecated, with all development moving to https://github.com/datapackages/datapackage-py/
